server:
  port: 8080

cors:
  allowed-origins: http://localhost:3000

spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  data:
    redis:
      port: 6379
      host: localhost
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: none   # 운영 DB는 none 또는 validate, 개발 초기에는 update
    properties:
      hibernate:
        format_sql: true   # SQL 포맷팅
        show_sql: true     # 실행되는 SQL 출력
    database-platform: org.hibernate.dialect.OracleDialect

oauth2:
  redirect:
    url: http://localhost:3000/oauth/redirect

file:
  # 실제 파일이 저장될 로컬 컴퓨터의 경로
  upload-dir: C:/Study/springboot/uploads
  # 클라이언트가 파일에 접근할 때 사용할 URL 경로
  resource-url-prefix: /images/
  download-uri-prefix: http://localhost:8080/images/
  # 임시 파일이 저장될 경로
  upload-dir-temp: C:/bons/BonsCore/uploads/temp
  temp-resource-url-prefix: /images/temp/
  temp-download-uri-prefix: http://localhost:8080/images/temp/